id: P010781
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5174
  title: ནང་ཆེན་སྐྱབས་མགོན་ཨ་ལྡེའུ་རིན་པོ་ཆེ་གྲུབ་རིགས་ཁྱུ་མཚོག་གི་རྣམ་ཐར།
  author: ''
  volumes:
    29e6ef42c10c4dd4be782ca584f99fa7:
      image_group_id: I3CN5176
      title: ''
      volume_number: 1
      total_pages: 216
